# this runs jobs in sequence
name: second

on: push

jobs:
  job1:
    name: First-job
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        uses: actions/checkout@v2
      - name: step 2
        run: env | sort
  job2:
    needs: job1
    name: Second-Job
    runs-on: windows-latest
    steps:
      - name: step 1
        uses: actions/checkout@v2
      - name: step 2 
        run: "Get-ChildItem Env: | Sort-Object Name"
